version: '3.9'
services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - movies-network

networks:
  movies-network:
    name: movies-network

volumes:
  postgres_db: